# Generated by Django 5.0.4 on 2024-05-03 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MyTaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("body", models.TextField()),
                ("created_in", models.DateTimeField(auto_now_add=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("high", "HIGH"),
                            ("medium", "MEDIUM"),
                            ("low", "LOW"),
                        ],
                        default="medium",
                        max_length=50,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.Case(
                        models.When(priority="high", then=models.Value(0)),
                        models.When(priority="medium", then=models.Value(1)),
                        default=models.Value(2),
                    )
                ],
            },
        ),
    ]
