# Generated by Django 5.0.4 on 2024-05-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personal_task", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mytaskmodel",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
